language: node_js
before_install:
 - rvm install 2.1
script: "./script/cibuild"
after_success: "./script/cideploy"
branches:
  only:
  - master
env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: sViph8Zdu27fLNfEVn1ZGsZqf3iSbY4SxegC/vO1zcR5F8Mru1yXq2bYLEyjVIJPTm/welukb0fuhnpzqgHAGeMU/WBb8gq2SLNng3vHdG1Kydkit7A7kHP8eGU/il3ueKEU7wP79wGSAOKsnGtWYt8yqMGC1AycWVFngzBDdzqUsrgVn8AMRpy2SH3uSYi0wA+wOYZMVPT4uWq9lbdoayMgY7AU4wK9gqZj6txt4ofFnsVkROG1RpdmCbTwto8rd5RQ0QWV7q16Nv1dwtfgRNrnlIA2t4W7DFGFS2Mu8lEosat023GJ1IgdNpMFf/U5psOLpXnevLBORGLoXGVoWKiTCx1/70lThD2PinsJVbY9b50keCaIWZLU2dAeLLD5uZcRbW+CwxAuKpa9sE9yKLN7/Zsf3fukXiVzHLahmkUUkL7WYHvNapVO+nXf6fMyKfytY8C3kd43CJpj9NLzCjfbPAZMSaxTWPubWRVnVlw/ddUncGq5YCngbY7CB2/0rrICAhxbKHkeLPwZrm12Hqi6Ji4qd/2rC+8Sj2aO4P0miqSUV7XTTq6cAQHitBA8MunuDqE96vio5hKaFzSeAcOnczb/xFgbdBm3MNkuQqSJtMG3W/KRp3t0D1QAi9WXed5Ry5S58ZnkWP873WKoKW1o/er/tjMVsFa0slClRGU=
