# Site settings
title: Computer Science Alliance
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://csa.ru" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
   - quote

exclude:
 - bower_components
 - bower.json
 - node_modules
 - .asset-cache
 - vendor
 - script
 - Gemfile
 - Gemfile.lock
 - TODO.md

assets:
  sources:
   - bower_components/jquery/dist
   - bower_components/rowGrid.js
   - bower_components/bootstrap-sass/assets/fonts
   - bower_components/bootstrap-sass/assets/images
   - bower_components/bootstrap-sass/assets/javascripts
   - bower_components/bootstrap-sass/assets/stylesheets


gems:
 - 'jekyll-assets'
 - 'polyglot'
 - 'jekyll-redirect-from'
 - 'jekyll-sitemap'
 - 'redcarpet'

prose:
  ignore:
    - bower.json
    - .gitignore
    - .travis.yml
    - Gemfile
    - _config.yml
    - script
    - _assets
    - csl
    - CNAME
    - TODO.md
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Заголовок"
    content:
      - name: "shortTitle"
        field:
          element: "text"
          label: "Короткий заголовок"
          help: "для отображения в меню"
      - name: "type"
        field:
          element: "select"
          label: "Категория"
          help: "Раздел меню, в которое добавится ссылка на страницу."
          options:
            - name: "Научная деятельность (верхнее меню, слева)"
              value: "science"
            - name: "Научно-организационная деятельность (верхнее меню, справа)"
              value: "activity"
            - name: "Нижнее меню (footer)"
              value: "footer"
      - name: "weight"
        field:
          element: "number"
          label: "Позиция в меню (вес)"
          help: "Чем больше вес, тем ближе к концу меню позиция."
          value: 1000
          type: "number"
      - name: "lang"
        field:
          element: "select"
          label: "Язык"
          help: "Страницы без указания языка отобразятся одновременно на русской и английской версии сайта."
          options:
            - name: "Русский"
              value: "ru"
            - name: "Английский"
              value: "en"
            - name: "-"
              value: ""

# i18n
languages: ["ru", "en"]
default_lang: "ru"
exclude_from_localization: ["javascript", "images", "css"]
