# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computer Science Alliance
email: 
description: > # this means to ignore newlines until "baseurl:"
  Computational Science Alliance (CSA) создан в 2004 г. на базе Института высокопроизводительных вычислений и Информационных Систем, который в свое время был преобразован из Института Высокопроизводительных Вычислений и Баз Данных, являвшегося российским лидером в инновации современных информационных технологий на основе высокопроизводительной компьютерной техники, Учебно-научного центра по вычислительной механике Института Теплофизики Экстремальных Состояний РАН Санкт-Петербургского политехнического университета и кафедры высокопроизводительных вычислений СПбГПУ. Деятельность направлена на развитие новых технологий в использовании суперкомпьютеров в различных областях науки и техники, осуществление информационной и вычислительной поддержки государственных учреждений, исследовательских и образовательных организаций. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://csa.ru" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
 - bower_components
 - bower.json
 - node_modules
 - .asset-cache
 - vendor
 - script
 - Gemfile
 - Gemfile.lock
 - TODO.md

assets:
  sources:
   - bower_components
   - _assets/javascripts


gems:
 - jekyll-assets


prose:
  ignore:
    - bower.json
    - .gitignore
    - .travis.yml
    - Gemfile
    - _config.yml
    - script
    - _assets
    - _sass
    - css
    - CNAME
    - TODO.md
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Заголовок"
    content:
      - name: "shortTitle"
        field:
          element: "text"
          label: "Короткий заголовок"
          help: "для отображения в меню"
      - name: "type"
        field:
          element: "select"
          label: "Категория"
          help: "Раздел меню, в которое добавится ссылка на страницу."
          options:
            - name: "Научная деятельность"
              value: "science"
            - name: "Научно-организационная деятельность"
              value: "activity"
            - name: "Нижнее меню (footer)"
              value: "footer"

