#!/bin/sh

set -e

root_dir=$(pwd)

# deploy to csa.ru
cd $root_dir
old_commit_message=$(git log -1 --pretty=%B)
repo_url="$REPO_URL"
git clone "$repo_url" _oldsite >/dev/null 2>&1
rsync -a --delete --exclude .git/ _site-csa/ _oldsite/
cd _oldsite
git config user.email "bot@csa.ru"
git config user.name "CSA bot"
git add --all
git commit -m "$old_commit_message"
git push "$repo_url" >/dev/null 2>&1

# deploy to apmath
cd $root_dir
keyfile=/tmp/apmath-id-rsa 
chmod 400 $keyfile
echo "StrictHostKeyChecking no" >> $HOME/.ssh/config
echo "IdentityFile $keyfile" >> $HOME/.ssh/config
rm -f _site-apmath/sitemap.xml
rm -f _site-apmath/CNAME
rm -f _site-apmath/en/sitemap.xml
rm -f _site-apmath/en/CNAME
rm -rf _site-apmath/children
rm -rf _site-apmath/en/children
echo 'DirectoryIndex index.html' > _site-apmath/.htaccess
rsync -az --delete _site-apmath/ "$APMATH_URL"
